### ISSUE TITLE
Alle im System enthaltenen Währungen werden in das App Objekt geladen

### ISSUE THREAD

**Issue by JVolke** [plentymarkets/plugin-io#895]
https://github.com/plentymarkets/plugin-io/blob/stable/src/Services/CheckoutService.php#L313

```
...
            "pattern" => $pattern,
            "symbols" => $symbols
        ];
...
```
symbols enthält aktuell alle in Plenty verfügbaren Währungen. 

In Ceres werden daher in das App Objekt aktuell alle Währung-Symbole in das App Objekt geladen. Sinnvoll wäre es hier nur die Währungen auszugeben, welche auch in der Shop Konfiguration aktiviert wurden.

@felixdausch @stentrop

**Comment by felixdausch** [comment]
Hallo @JVolke ,

danke für den Hinweis! Ich habe die Funktion angepasst und filtere jetzt die inaktiven Währungen raus.
https://github.com/plentymarkets/plugin-io/pull/898

Viele Grüße
Felix
